wandb_version: 1

env_id:
  desc: null
  value: CartPole-v1
tao:
  desc: null
  value: 0.1
eta:
  desc: null
  value: 0.9
inference_iterations:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.8
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725022479
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 16
      - 23
      4: 3.10.14
      5: 0.17.8
      8:
      - 5
      13: darwin-arm64
