wandb_version: 1

env_name:
  desc: null
  value: CartPole-v1
buffer_size:
  desc: null
  value: 1000
batch_size:
  desc: null
  value: 64
gamma:
  desc: null
  value: 0.99
x_lr:
  desc: null
  value: 0.01
p_lr:
  desc: null
  value: 0.001
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.17.6
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1724238862
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.11.5
      5: 0.17.6
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
